
app.factory('carFactory', function () {
	
	return [
		{
			name: "BMW",
			img: "car_01.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: true,
			conditioner: true,
			wheels: true,
			multiWheel: true,
			parktronic: false,
			abs: true,
			signaling: true,
			service: false,
			asterPlus: true,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "Porsche",
			img: "car_02.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: false,
			conditioner: true,
			wheels: true,
			multiWheel: true,
			parktronic: true,
			abs: true,
			signaling: true,
			service: true,
			asterPlus: true,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "Mercedes",
			img: "car_03.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: true,
			conditioner: true,
			wheels: false,
			multiWheel: true,
			parktronic: true,
			abs: false,
			signaling: true,
			service: true,
			asterPlus: true,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "audi",
			img: "car_04.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: false,
			conditioner: true,
			wheels: true,
			multiWheel: true,
			parktronic: true,
			abs: true,
			signaling: true,
			service: true,
			asterPlus: true,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "porsche_01",
			img: "car_05.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: true,
			conditioner: false,
			wheels: true,
			multiWheel: true,
			parktronic: false,
			abs: true,
			signaling: true,
			service: true,
			asterPlus: false,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "porsche_02",
			img: "car_06.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: false,
			conditioner: true,
			wheels: true,
			multiWheel: true,
			parktronic: true,
			abs: true,
			signaling: true,
			service: false,
			asterPlus: true,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "Lifan",
			img: "car_07.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: false,
			conditioner: true,
			wheels: true,
			multiWheel: true,
			parktronic: true,
			abs: false,
			signaling: true,
			service: true,
			asterPlus: true,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		},
		{
			name: "BMW_01",
			img: "car_08.jpg",
			priceBefo: "2 800 000 тг",
			price: "2 500 000 тг",
			mileage: "94 797",
			body: "Внедорожник",
			engine: "2.4 л., Бензин (170 л.с.)",
			drive: "Поный привод",
			climateControl: true,
			conditioner: true,
			wheels: false,
			multiWheel: true,
			parktronic: false,
			abs: true,
			signaling: true,
			service: true,
			asterPlus: false,
			salon: "Aster Expert",
			time: "Ежедневно с 8.00 до 22.00",
			telephone: "+7 (495) 229-22-44"
		}
	];

});
